### ISSUE TITLE
request failed 400 BAD_REQUEST ERROR

### ISSUE THREAD

**Issue by Franci000** [codemakerai/codemaker-cli#1]
Hi , I don't know how to resolve this error,  also I don't know if this error is caused by my or your server. 
This happen when I create the documentations with the command "codemaker generate docs ciao.java"

I think is maybe caused by the code you sent me by email, but I don't know.

![image](https://user-images.githubusercontent.com/85842982/226847488-59fd6124-e27b-4b3d-9009-371b666c1dd7.png)

**Comment by codemakerai-dev** [comment]
Hello @Franci000.

Thank you for reporting the problem.  Could you please confirm that the issue has been resolved for you?

**Comment by codemakerai-dev** [comment]
Thank you for taking the time to report the problem. Please re-open the ticket in case you still face the problem.
